sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: centos
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tDL3TiDjLJZnnTQGX7w
    access-key-secret: il5TRsjDPUTlD0SHuBG8FOhat3qpSE
    bucket-name: sky-take-out-kendrick
  redis:
    host: centos
    password: 123321
    port: 6379
    database: 10
  wechat:
      appid: wx91a7f54d01bd383b
      secret: 93b47528b0b8398fd3ffd517f334a40b
      mchid: 1561414331
      mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
      privateKeyFilePath: D:\pay\apiclient_key.pem
      apiV3Key: CZBK51236435wxpay435434323FFDuv3
      weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
      notifyUrl: https://23ebc1fe.r16.cpolar.top/notify/paySuccess
      refundNotifyUrl: https://23ebc1fe.r16.cpolar.top/notify/refundSuccess
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: Yn58xGQt2m2xTlaBVLhNuRSYvfZhkXhS
